// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace mock_signets.Migrations
{
    [DbContext(typeof(SignetsContext))]
    partial class SignetsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Models.Entities.EvaluationCours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CodeEtudiant")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CodeProf")
                        .HasColumnType("TEXT");

                    b.Property<string>("Enseignant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Groupe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sigle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeEvaluation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("EvaluationCours");
                });

            modelBuilder.Entity("Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeAccesUniversel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePermanent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Masculin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotPasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoldeTotal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.Entities.EvaluationCours", b =>
                {
                    b.HasOne("Models.Entities.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
